name: Scheduled Branch Cleanup

on:
  schedule:
    - cron: "* * * * *" # 
  workflow_dispatch: # Allows manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Delete Stale Branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch all remote branches
          git fetch --prune

          # Get a list of branches (excluding main and protected ones)
          branches=$(git branch -r | grep -v "main\|dev\|qa\|staging" | awk '{print $1}' | sed 's/origin\///')

          for branch in $branches; do
            # Get the last commit date
            last_commit_date=$(git log -1 --format=%ct origin/$branch)
            current_date=$(date +%s)
            age=$(( (current_date - last_commit_date) / 86400 ))

            # Delete branches older than 30 days
            if [ $age -gt 1 ]; then
              echo "Deleting branch: $branch (Last commit: $age days ago)"
              git push origin --delete $branch
            fi
          done
